name: get_leetcode_data

on:
  schedule:
    - cron: '0 */8 * * *' # Runs every 8 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script
      run: python3 leetcode_status.py yohanlong # Replace with your script name

    - name: Commit and Push changes
      run: |
        git config --global user.email "hlong25@wisc.edu"
        git config --global user.name "Alfr3doK1ng"
        git add leetcode_data.json
        git diff --staged --exit-code || git commit -m "Update leetcode_data.json"
        git push
